Default: &defaults
  database: RenewalDebates.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: RenewalDebates_test.sqlite3
  <<: *defaults

Staging:
  database: RenewalDebates_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: RenewalDebates_production.sqlite3
  poolsize: 100
  <<: *defaults
